name: Om Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push version
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dipendrac3/cicd-test:${{github.run_number}}

      - name: Build and push latest
        id: build-image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dipendrac3/cicd-test:latest
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      
      - name: Fill in the new image ID in the Amazon ECS task definition2
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition
        with:
          task-definition: task-definition.json
          container-name: nodejs
          image: dipendrac3/cicd-test:latest

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: nodejs
          image: ${{ steps.build-image.outputs.image }}
          

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: test
          cluster: nodejs-cluster-dev
          wait-for-service-stability: true