name: Om Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push version
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dipendrac3/cicd-test:${{github.run_number}}

      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dipendrac3/cicd-test:dev